const contracts = [
  {
    id: "0",
    title: "Contrat",
    name: "Doe",
    firstname: "John",
    dateOfBirth: "15/02/1987",
    phoneNumber: "0652458963",
    email: "johndoe@gmail.com",
    address: "4 rue de la mairie, 84256, Villun",
    vehiculeType: "Scooter",
    model: "BRUMAIRE 125 SMART SCOOTER",
    numberPlate: "AF-222-WF",
    contractNumber: "9985",
    contractStartDate: "01/03/2021",
    price: "29,90€",
    payment: "Mensuel",
    bonusMalus: "0.8",
    guarantees: "Aucune garantie",
  },
  {
    id: "1",
    title: "Contrat",
    name: "Doe",
    firstname: "John",
    dateOfBirth: "15/02/1987",
    phoneNumber: "0652458963",
    email: "johndoe@gmail.com",
    address: "4 rue de la mairie, 84256, Villun",
    vehiculeType: "Scooter",
    model: "YAMAHA 900 MT 09",
    numberPlate: "KF-896-PN",
    contractNumber: "9853",
    contractStartDate: "09/11/2021",
    price: "29,90€",
    payment: "Mensuel",
    bonusMalus: "0.8",
    guarantees: "Aucune garantie",
  },
];
export default contracts;
